[build]
builder = "dockerfile"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:$PORT --timeout 120 --workers 1 server:app"
healthcheckPath = "/health"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
